### ISSUE TITLE
how to use with KickAssembler

### ISSUE THREAD

**Issue by luca-i** [64kramsystem/vscode-markdown-code-blocks-asm-syntax-highlighting#6]
Hi, I'm editing some asm files that use KickAssembler syntax provided by [KickAss (C64)](https://marketplace.visualstudio.com/items?itemName=CaptainJiNX.kickass-c64) extension.
I can't figure out how to configure your plugin to use that syntax in my markdown files.
Could you please help me?

Thank you, Luca-

**Comment by 64kramsystem** [comment]
Hello!

I've added the same functionality to another project. You can find the PR [here](https://github.com/maziac/asm-code-lens/pull/65/files).

**Comment by luca-i** [comment]
Thank you, I'll check it out!

**Comment by 64kramsystem** [comment]
It should be fairly easy to copy the PR content. Right now I don't remember the logic exactly :sweat_smile: (actually, at all), but I think the only thing to be done is to:

- find out the identifier for KickAss' asm grammar
- replace `source.asm` with the identifier

If the identifier is `source.asm`,  I think you may get away with a straight copypasta :grin: (of course, packaging etc. is a separate task)
